Models/Manager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HarnyCardApplication.Models
{
    public class Manager : BaseEntity
    {
        public int UserId{get; set;}
        public User User{get; set;}
        public double Wallet{get; set;}

    }
}

Controllers/CardController.cs
using System.Security.Claims;
using HarnyCardApplication.Dtos;
using HarnyCardApplication.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HarnyCardApplication.Controllers
{
    public class CardController : Controller
    {
        private readonly ICardService _cardService;
        public CardController(ICardService cardService)
        {
            _cardService = cardService;
        }
        public IActionResult CreateCard()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateCard(CreateCardRequestModel model)
        {
            var response = await _cardService.Create(model);
            if (response.Status == true)
            {
                TempData["success"] = $"Created Successfully";
                return RedirectToAction("ManagerBoard", "Manager");
            }
            else
            {
                TempData["error"] = "Wrong Input";
                return View();
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            _cardService.Delete(id);
            ViewBag.Message = "Card deleted successfully";
            return RedirectToAction();
        }
        public async Task<IActionResult> Get(int id)
        {
            var card = await _cardService.Get(id);
            if (card.Status == true)
            {
                return View(card.Data);
            }
            return View();
        }
        public async Task<IActionResult> BuyCard()
        {
            var card = await _cardService.GetIsAvailableCards();
            return View(card.Data);
        }
        [HttpPost]
        public async Task<IActionResult> BuyCard(BuyCardRequestModel buyCardRequest, int id)
        {
            var Id = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var card = await _cardService.BuyCard(buyCardRequest, int.Parse(Id), id);
            if (card == null)
            {
                ViewBag.error = "invalid";
                return View();
            }
            TempData["CardPin"] = card.Message;
            return RedirectToAction("BuyCard");
        }
        public async Task<IActionResult> GetAll()
        {
            var card = await _cardService.GetAll();
            return View(card);
        }
         public async Task<IActionResult> GetCustomerCards()
        {
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var card = await _cardService.GetCustomerCards(int.Parse(userId));
            return View(card);
        }
        public async Task<IActionResult> GetCardByPin(string pin)
        {
            var card = await _cardService.GetCardByPin(pin);
            if (card.Status == true)
            {
                return View(card.Data);
            }
            return View();
        }
    }
}

Controllers/CategoryController.cs
using HarnyCardApplication.Dtos;
using HarnyCardApplication.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HarnyCardApplication.Controllers
{
    public class CategoryController : Controller
    {
        public ICategoryService _categoryService;
        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateCategoryRequestModel model)
        {
            var createCategory = await _categoryService.Create(model);
            if (createCategory.Status == true)
            {
                TempData["Message"] = createCategory.Message;
                return RedirectToAction("ManagerBoard", "Manager");
            }
            return View();

        }
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _categoryService.Delete(id);
            if (response.Status == false)
            {
                TempData["Message"] = response.Message;
                return View();
            }
            return RedirectToAction("");
        }
        public IActionResult Update()
        {
            return View();
        }
        public async Task<IActionResult> Update(int id, UpdateCategoryRequestModel model)
        {
            var response = await _categoryService.Update(id, model);
            if (response.Status == false)
            {
                TempData["Message"] = response.Message;
                return View();
            }
            return RedirectToAction("");
        }
    }
}

Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarnyCardApplication.Dtos;
using HarnyCardApplication.Services.Implementations;
using HarnyCardApplication.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HarnyCardApplication.Controllers
{
    public class ManagerController : Controller
    {
        private readonly IManagerService _managerService;
        public ManagerController(IManagerService managerService)
        {
            _managerService = managerService;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateManagerRequestModel model)
        {
            if (model != null)
            {
                var create = await _managerService.Create(model);
                TempData["success"] = $"{model.FirstName} {model.LastName} Created Successfully";
                TempData.Keep();
                return RedirectToAction("Login", "User");
            }
            else
            {
                TempData["error"] = "Wrong Input";
                return View();
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _managerService.Delete(id);
            ViewBag.Message = "Customer deleted successfully";
            return RedirectToAction();
        }
        public async Task<IActionResult> Get(int id)
        {
            var customer = await _managerService.Get(id);
            if (customer.Status == true)
            {
                return View(customer.Data);
            }
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            var customer = await _managerService.GetAll();
            if (customer.Status == true)
            {
                return View(customer.Data);
            }
            return View();
        }
        public IActionResult Update()
        {
            return View();
        }
        public async Task<IActionResult> Update(int id, UpdateManagerRequestModel model)
        {
            await _managerService.Update(id, model);
            ViewBag.Message = "Customer edited successfully";
            return RedirectToAction();
        }

        public IActionResult ManagerBoard()
        {
            return View();
        }
    }
}

Controllers/NetworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HarnyCardApplication.Dtos;
using HarnyCardApplication.Services.Implementations;
using HarnyCardApplication.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace HarnyCardApplication.Controllers
{
    public class NetworkController : Controller
    {
        private readonly INetworkService _networkService;
        public NetworkController(INetworkService networkService)
        {
            _networkService = networkService;
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateNetwork(CreateNetworkRequestModel model)
        {
            var response = await _networkService.Create(model);
            if (response.Status == true)
            {
                TempData["success"] = $"Created Successfully and your card pin is {response.Data.Name}";
                return RedirectToAction("ManagerBoard", "Manager");
            }
            else
            {
                TempData["error"] = "Wrong Input";
                return View();
            }
        }
        public async Task<IActionResult> Delete(int id)
        {
            await _networkService.Delete(id);
            ViewBag.Message = "Customer deleted successfully";
            return RedirectToAction();
        }
        public async Task<IActionResult> Get(int id)
        {
            var customer = await _networkService.Get(id);
            if (customer.Status == true)
            {
                return View(customer.Data);
            }
            return View();
        }
        public IActionResult GetAll()
        {
            var card = _networkService.GetAll();
            return View(card);
        }
        public IActionResult Update()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateNetworkRequestModel model)
        {
            var response = await _networkService.Update(id, model);
            if (response.Status == false)
            {
                TempData["Message"] = response.Message;
                return View();
            }
            return RedirectToAction("");
        }
    }
}

Views/Manager/Create.cshtml
@model HarnyCardApplication.Dtos.CreateManagerRequestModel;


@if (ViewData != null)
{
    <h2>@TempData["success"]</h2>
}

<body style="background-color: rgb(255, 255, 255);">

    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] AirtimeApp</title>

    </head>
    <div class="container">
        <div class="row justify-content-center">
            <div class=" card col-md-6">
                <div class="card-body " style="background-color: rgb(252, 249, 249);">
                    <div class="bg-light">
                        <h1 class="tagcolor" style="color:rgb(197, 148, 148)">Create Manager</h1>
                        <p class="tagcolor" style="color:rgb(197, 148, 148))">Please fill in this form to SignUp as a Manager.</p>
                        <hr class="tagcolor" style="color:rgb(197, 148, 148)">
                    </div>
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-row">
                            <div class="form-group col-sm-6">
                                <label asp-for="FirstName" class="control-label"></label>
                                <input asp-for="FirstName" class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-6">
                                <label asp-for="LastName" class="control-label"></label>
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-6">
                                <label asp-for="PhoneNumber" class="control-label"></label>
                                <input asp-for="PhoneNumber" class="form-control" />
                                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-6">
                                <label asp-for="Email" class="control-label"></label>
                                <input asp-for="Email" class="form-control" />
                                <span asp-validation-for="Email" class="text-danger"></span>
                            </div>
                            <div class="form-group col-sm-6">
                                <label asp-for="Password" class="control-label"></label>
                                <input type="password" asp-for="Password" class="form-control" />
                                <span asp-validation-for="Password" class="text-danger"></span>
                            </div><br>


                            <div class="form-group ">
                                <input href="#myModal" type="submit" value="Sign Up"
                                    class="btn btn-success trigger-btn col-sm-12" data-toggle="modal" />
                            </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

</body>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Manager/Details.cshtml
@model HarnyCardApplication.Dtos.ManagerDto;


<div>
    <h6>Customer Profile</h6>
    
    <hr/>
   <dl>
         <dt>
            <h4>@Html.DisplayNameFor(model => model.FirstName)</h4>
        </dt>
         <dd>
            <h4>@Html.DisplayFor(model => model.FirstName) </h4>
        </dd>
         <dt>
            <h4>@Html.DisplayNameFor(model => model.LastName)</h4>
        </dt>
         <dd>
            <h4>@Html.DisplayFor(model => model.LastName) </h4>
        </dd>
        <dt>
            <h4>@Html.DisplayNameFor(model => model.Email)</h4>
        </dt>
         <dd>
            <h4>@Html.DisplayFor(model => model.Email) </h4>
        </dd>
        <dt>
            <h4>@Html.DisplayNameFor(model => model.PhoneNumber)</h4>
        </dt>
         <dd>
            <h4>@Html.DisplayFor(model => model.PhoneNumber) </h4>
        </dd>
   </dl>
</div>

Views/Manager/ManagerBoard.cshtml
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        button:hover {
            cursor: pointer;
            justify-content: space-between;
            gap: 15px;
        }
        .first:hover{
            background-color: rgb(70, 15, 221);
        }
        .second:hover{
            background-color: rgb(68, 153, 68);
        }
        .third:hover{
            background-color: cyan;
        }
        .fourth:hover{
            background-color: rgb(196, 80, 80);
        }
        .fifth:hover{
            background-color: rgb(102, 170, 230);
        }

        button {
            height: 100px;
            width: 200px;
            border-radius: 15px;
        }

        h4 {
            display: flex;
            justify-content: center;
        }
    </style>
</head>

<body>
    <div id="my-container">
        <form>
            @if (@TempData["Success"] != null)
            {
                <h4 style="background-color: white;">@TempData["Success"]</h4>
            }
            <h4 style="color: white !important;">Manager LANDING PAGE</h4>
            <div class="button">
                <button class="fifth"><a asp-controller="Network" asp-action="Create" class="mang-a">Create Network</a></button>
                <button class="first"><a asp-controller="Category" asp-action="Create" class="mang-a">Create Category</a></button>
                <button class="second"><a asp-controller="Card" asp-action="CreateCard" class="mang-a">Create Card</a></button>
                <button class="third"><a asp-controller="Customer" asp-action="GetAll" class="mang-a">View All Customers</a></button>
                <button class="fourth"><a asp-controller="Card" asp-action="GetAll" class="mang-a">View All Cards</a></button>
           
            </div>
        </form>
    </div>
</body>

</html>